import PropTypes from 'prop-types';
import {useMemo} from 'react';

import scriptContent from './byline-script.js?raw';

/**
 * Only use once per App.
 * Puts the byline at the bottom of the article.
 */
function BylineSnippet({className = 'zg-byline'}) {
  const modifiedScriptContent = useMemo(() => {
    return scriptContent.replace(/CLASSNAME/g, className);
  }, [className]);

  return <script dangerouslySetInnerHTML={{__html: modifiedScriptContent}} />;
}

BylineSnippet.propTypes = {
  /** className for newly generated byline element */
  className: PropTypes.string,
};

export default BylineSnippet;
